export const FETCH_MOVIE_LIST_REQUEST = "FETCH_MOVIE_LIST_REQUEST"
export const FETCH_MOVIE_LIST_SUCCESS = "FETCH_MOVIE_LIST_SUCCESS"
export const FETCH_MOVIE_LIST_FAILURE = "FETCH_MOVIE_LIST_FAILURE"

export const ADD_LIKE_MOVIE = "ADD LIKE MOVIE";
export const DELETE_LIKE_MOVIE = "DELETE LIKE MOVIE";
export const ADD_BLOCK_MOVIE = "ADD BLOCK MOVIE";
export const DELETE_BLOCK_MOVIE = "DELETE BLOCK MOVIE";

export const SET_CURRENT_PAGE = 'SET CURRENT PAGE';
export const SORT_MOVIE_LIST = 'SORT MOVIE LIST';

